# See: https://docs.github.com/en/actions/writing-workflows
---
name: Prepare Homebrew

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ${{ github.ref_name }}
      tap_owner:
        required: false
        type: string
        description: Homebrew tap owner
        default: ${{ github.repository_owner }}
      tap_name:
        required: false
        type: string
        description: Homebrew tap name
        default: tap
      formula_owner:
        required: false
        type: string
        default: ${{ github.repository_owner }}
      formula_name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
    outputs:
      bump_formula:
        value: ${{ jobs.prepare-homebrew-formula.outputs.bump_formula }}
    secrets:
      ASIMOV_APP_ID:
        required: true
      ASIMOV_APP_PRIVATE_KEY:
        required: true

jobs:
  prepare-homebrew-formula:
    name: Prepare Homebrew
    uses: asimov-platform/actions/.github/workflows/prepare-homebrew-formula.yaml@master
    secrets:
      ASIMOV_APP_ID: ${{ secrets.ASIMOV_APP_ID }}
      ASIMOV_APP_PRIVATE_KEY: ${{ secrets.ASIMOV_APP_PRIVATE_KEY }}
    with:
      version: ${{ inputs.version }}
      tap_owner: ${{ inputs.tap_owner }}
      tap_name: ${{ inputs.tap_name }}
      formula_owner: ${{ inputs.formula_owner }}
      formula_name: ${{ inputs.formula_name }}
