# See: https://docs.github.com/en/actions/writing-workflows
---
name: Update Scoop bucket

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ${{ github.ref_name }}
      assets:
        required: true
        type: string

jobs:
  update-scoop-bucket:
    uses: asimov-platform/actions/.github/workflows/update-scoop-bucket.yaml@master
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      assets: ${{ inputs.assets }}
