# See: https://docs.github.com/en/actions/writing-workflows
---
name: Update Homebrew tap

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ${{ github.ref_name }}
      bump_formula:
        required: false
        type: boolean
        default: true
      tap_owner:
        required: false
        type: string
        description: Homebrew tap owner
        default: ${{ github.repository_owner }}
      tap_name:
        required: false
        type: string
        description: Homebrew tap name
        default: tap
      formula_owner:
        required: false
        type: string
        default: ${{ github.repository_owner }}
      formula_name:
        required: false
        type: string
        default: ${{ github.event.repository.name }}

jobs:
  update-homebrew-tap:
    uses: asimov-platform/actions/workflows/update-homebrew-tap.yaml@master
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      bump_formula: ${{ inputs.bump_formula }}
      tap_owner: ${{ inputs.tap_owner }}
      tap_name: ${{ inputs.tap_name }}
      formula_owner: ${{ inputs.formula_owner }}
      formula_name: ${{ inputs.formula_name }}
